[package]
name = "json-seq"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.57"
serde = "1.0.115"

